app:
  # dev mode
  # if not exist, only use app.yaml
  devMode: dev
  port: 9000
  # database
  # db
  db:
#    driver: mysql # mysql/postgres
    maxIdleConn: 20
    maxOpenConn: 100
    # database name
    name: gt
  # mongodb
  mongo:
    name: gt
  # upload filepath
  filepath: static/file/
  log:
    # log director
    director: log
    # log max day
    max-age: 7
    #　log in terminal/file/all
    log-in: all
